CREATE TABLE assessment_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    topic_id bigint NOT NULL REFERENCES topic(id),
    status varchar(20) NOT NULL DEFAULT 'CREATED'
        CHECK (status IN ('CREATED','IN_PROGRESS','PROCESSING','COMPLETED')),
    attempt_id uuid,
    processing_expires_at timestamptz,
    last_failure_code varchar(40),
    last_failure_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX assessment_session_user_topic_idx ON assessment_session(user_id, topic_id);

-- Snapshot of an issued question so a session stays reproducible even if the
-- question bank changes later. session_id+order_index fixes display order;
-- session_id+question_id blocks the same question being issued twice.
CREATE TABLE assessment_question (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL REFERENCES assessment_session(id),
    question_id bigint NOT NULL REFERENCES question(id),
    order_index int NOT NULL CHECK (order_index >= 0),
    measurement_area_snapshot varchar(40) NOT NULL
        CHECK (measurement_area_snapshot IN ('VOCABULARY','BACKGROUND_KNOWLEDGE','COMPREHENSION')),
    prompt_snapshot text NOT NULL CHECK (btrim(prompt_snapshot) <> ''),
    version_snapshot varchar(80) NOT NULL CHECK (btrim(version_snapshot) <> ''),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(session_id, order_index),
    UNIQUE(session_id, question_id)
);

-- One answer per issued question; PUT re-submission replaces it in place.
-- Self-report format: the user marks whether they know the concept, no grading.
CREATE TABLE assessment_answer (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_question_id bigint NOT NULL UNIQUE REFERENCES assessment_question(id),
    knows_concept boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER assessment_session_updated BEFORE UPDATE ON assessment_session
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER assessment_answer_updated BEFORE UPDATE ON assessment_answer
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
