CREATE TABLE question (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id bigint NOT NULL REFERENCES topic(id),
    measurement_area varchar(40) NOT NULL
        CHECK (measurement_area IN ('VOCABULARY','BACKGROUND_KNOWLEDGE','COMPREHENSION')),
    difficulty int NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
    prompt text NOT NULL CHECK (btrim(prompt) <> ''),
    version varchar(80) NOT NULL CHECK (btrim(version) <> ''),
    active boolean NOT NULL DEFAULT false,
    demo_key varchar(80) UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Assessment session creation reads only the active question set for a topic/area.
CREATE INDEX question_topic_area_active_idx ON question(topic_id, measurement_area) WHERE active;

CREATE TRIGGER question_updated BEFORE UPDATE ON question
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
